spring:
  datasource:
    url: jdbc:mysql://localhost:3306/everytime?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    generate-ddl: true
    show-sql: true